services:
  postgres-responder:
    image: postgres:latest
    container_name: postgres-responder
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=credit_score
      - POSTGRES_PASSWORD=admin
    ports:
      - 5436:5432
    volumes:
      - volume-responder:/var/lib/postgresql/data
      - ./data-responder/responders.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  notebook-analysis:
    image: jupyter/minimal-notebook:latest
    container_name: notebook-analysis
    ports:
      - 8888:8888
    volumes:
      - ./credit-score:/home/jovyan/work
    command: bash -c "pip install -r /home/jovyan/work/requirements.txt && jupyter notebook"
    depends_on:
      - postgres-responder
    networks:
      - app-network

networks:
  app-network:

volumes:
  volume-responder:
    name: volume-responder
